# service_treatments_map.py

SERVICE_TREATMENT_MAP = {
    "2": "acupressure_treatment",
    "3": "single_point_treatment",
    "4": "colour_treatment",
    "5": "auricular_treatment",
    "6": "seed_treatment",
    "7": "mudra_treatment",
    "8": "yoga_treatment",
    "9": "pranayama_treatment",
}


food_metabolism_map = [
    {"pattern_number": 1, "fat": "high", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 2, "fat": "high", "carbo": "normal", "protein": "low"},
    {"pattern_number": 3, "fat": "normal", "carbo": "normal", "protein": "high"},
    {"pattern_number": 4, "fat": "normal", "carbo": "high", "protein": "normal"},
    {"pattern_number": 5, "fat": "normal", "carbo": "low", "protein": "normal"},
    {"pattern_number": 6, "fat": "low", "carbo": "low", "protein": "normal"},
    {"pattern_number": 7, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 8, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 9, "fat": "low", "carbo": "normal", "protein": "low"},
    {"pattern_number": 10, "fat": "normal", "carbo": "normal", "protein": "low"},
    {"pattern_number": 11, "fat": "normal", "carbo": "low", "protein": "normal"},
    {"pattern_number": 12, "fat": "normal", "carbo": "low", "protein": "low"},
    {"pattern_number": 13, "fat": "high", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 14, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 15, "fat": "high", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 16, "fat": "normal", "carbo": "high", "protein": "normal"},
    {"pattern_number": 17, "fat": "normal", "carbo": "normal", "protein": "low"},
    {"pattern_number": 18, "fat": "normal", "carbo": "normal", "protein": "high"},
    {"pattern_number": 19, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 20, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 21, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 22, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 23, "fat": "low", "carbo": "normal", "protein": "low"},
    {"pattern_number": 24, "fat": "low", "carbo": "normal", "protein": "low"},
    {"pattern_number": 25, "fat": "high", "carbo": "high", "protein": "normal"},
    {"pattern_number": 26, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 27, "fat": "normal", "carbo": "low", "protein": "normal"},
    {"pattern_number": 28, "fat": "high", "carbo": "high", "protein": "normal"},
    {"pattern_number": 29, "fat": "normal", "carbo": "high", "protein": "low"},
    {"pattern_number": 30, "fat": "normal", "carbo": "high", "protein": "normal"},
    {"pattern_number": 31, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 32, "fat": "normal", "carbo": "low", "protein": "normal"},
    {"pattern_number": 33, "fat": "normal", "carbo": "low", "protein": "low"},
    {"pattern_number": 34, "fat": "low", "carbo": "low", "protein": "normal"},
    {"pattern_number": 35, "fat": "normal", "carbo": "normal", "protein": "low"},
    {"pattern_number": 36, "fat": "normal", "carbo": "low", "protein": "low"},
    {"pattern_number": 37, "fat": "high", "carbo": "normal", "protein": "low"},
    {"pattern_number": 38, "fat": "normal", "carbo": "low", "protein": "normal"},
    {"pattern_number": 39, "fat": "normal", "carbo": "normal", "protein": "low"},
    {"pattern_number": 40, "fat": "normal", "carbo": "normal", "protein": "low"},
    {"pattern_number": 41, "fat": "normal", "carbo": "normal", "protein": "low"},
    {"pattern_number": 42, "fat": "normal", "carbo": "normal", "protein": "low"},
    {"pattern_number": 43, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 44, "fat": "normal", "carbo": "low", "protein": "normal"},
    {"pattern_number": 45, "fat": "normal", "carbo": "low", "protein": "normal"},
    {"pattern_number": 46, "fat": "normal", "carbo": "normal", "protein": "low"},
    {"pattern_number": 47, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 48, "fat": "normal", "carbo": "low", "protein": "low"},
    {"pattern_number": 49, "fat": "low", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 50, "fat": "normal", "carbo": "low", "protein": "normal"},
    {"pattern_number": 51, "fat": "low", "carbo": "normal", "protein": "low"},
    {"pattern_number": 52, "fat": "high", "carbo": "normal", "protein": "normal"},
    {"pattern_number": 53, "fat": "normal", "carbo": "normal", "protein": "high"},
    {"pattern_number": 54, "fat": "normal", "carbo": "normal", "protein": "low"},
    {"pattern_number": 55, "fat": "normal", "carbo": "low", "protein": "low"},
    {"pattern_number": 56, "fat": "normal", "carbo": "normal", "protein": "high"},
    {"pattern_number": 57, "fat": "normal", "carbo": "low", "protein": "low"},
    {"pattern_number": 58, "fat": "low", "carbo": "normal", "protein": "low"},
    {"pattern_number": 59, "fat": "normal", "carbo": "normal", "protein": "low"},
    {"pattern_number": 60, "fat": "normal", "carbo": "low", "protein": "low"},
]
