"""
Django settings for oohy_product project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!


SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition

CUSTOM_APPS = [
    # appplication specific apps
    "social_django",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",
    # all auth related apps
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    "allauth.socialaccount.providers.twitter",
    "allauth.socialaccount.providers.instagram",
    "django_otp",
    "django_otp.plugins.otp_totp",
    "oohy_product",
    "authentication",
    "user_profile",
    "patients",
    "pulse_service",
    "pulse_payments",
    "django_extensions",
    "razorpay",
    "report_service",
    "device_management",
    "django_select2",
    "dynamic_report_service",
    "corsheaders",
]

ALLOWED_HOSTS = [
    "127.0.0.1",
    "13.202.135.108",
    "test-backend-baa.online",
    "localhost",
    "www.test-backend-baa.online",
    "ae17-2401-4900-1f29-4a9c-88ff-c378-a631-7f1a.ngrok-free.app",
    "testserver",
    "nadiswarapro-backend.online",
]


# Razorpay API credentials
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_SECRET_KEY")
RAZORPAY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "your_razorpay_key_secret")

DEFAULT_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

INSTALLED_APPS = DEFAULT_APPS + CUSTOM_APPS

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    "social_core.backends.google.GoogleOAuth2",
    "django.contrib.auth.backends.ModelBackend",  # Keep the default backend
    "allauth.account.auth_backends.AuthenticationBackend",
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # "oauth2_provider.middleware.OAuth2TokenMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
    "authentication.middleware.AccessTokenBlacklistMiddleware",
    "middleware.custom_middleware.GetSuperUserStatusMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]
CORS_ALLOWED_ORIGINS = [
    "http://test-backend-baa.online",
    "http://13.202.135.108:8000",
    "http://www.test-backend-baa.online",
]

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ["email", "profile"]

ROOT_URLCONF = "oohy_product.urls"

CLIENT_ID = os.environ.get(
    "562493710511-fp0ibcim43hl4kubjqmbetb64ilnjhb4.apps.googleusercontent.com"
)
CLIENT_SECRET = os.environ.get("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")

CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

CSRF_TRUSTED_ORIGINS = [
    "https://test-backend-baa.online",
    "https://nadiswarapro-backend.online",
]


WSGI_APPLICATION = "oohy_product.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


AUTH_USER_MODEL = "authentication.CustomUser"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
    # other directories if any...
]


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "weasyprint": {
            "handlers": ["console"],
            "level": "ERROR",  # or 'CRITICAL' if you want to silence almost everything
            "propagate": False,
        },
        "fontTools": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "__main__": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "": {  # catch-all for any logger name
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


import os
from dotenv import load_dotenv

# Load .env variables
load_dotenv()

# Backblaze B2 Configuration
B2_ACCOUNT_ID = os.getenv("B2_ACCOUNT_ID")
B2_APPLICATION_KEY = os.getenv("B2_APPLICATION_KEY")
B2_BUCKET_NAME = os.getenv("B2_BUCKET_NAME")
B2_ENDPOINT = os.getenv("B2_ENDPOINT", "https://s3.us-east-005.backblazeb2.com")

# Ensure credentials are loaded
if not all([B2_ACCOUNT_ID, B2_APPLICATION_KEY, B2_BUCKET_NAME]):
    raise ValueError("Backblaze B2 credentials are missing! Check your .env file.")

# Set Backblaze as the default storage
DEFAULT_FILE_STORAGE = "report_service.storage_backends.BackblazeB2Storage"

# Twilio Configuration
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    "email",
    "profile",
    "profile",
    "openid",
    "https://www.googleapis.com/auth/drive",  # Access Google Drive
    "https://www.googleapis.com/auth/calendar",  # Access Google Calendar
]

# Optional: Add the scopes you need
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]

LOGIN_URL = "auth/google/"
LOGOUT_URL = "logout/"
LOGIN_REDIRECT_URL = "home/"  # Define a redirect URL after login

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "APP": {
            "client_id": os.environ.get(
                "562493710511-fp0ibcim43hl4kubjqmbetb64ilnjhb4.apps.googleusercontent.com"
            ),
            "secret": os.environ.get("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"),
        },
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = True  # Change to True if using TLS
EMAIL_USE_SSL = False

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
SOCIAL_AUTH_GOOGLE_OAUTH2_USE_UNIQUE_USER_ID = True

#
# DATABASES = {
#
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': os.environ.get('NAME'),
#         'USER': os.environ.get('USER'),
#         'PASSWORD': os.environ.get('PASSWORD'),
#         'HOST': os.environ.get('HOST'),
#         'PORT': os.environ.get('PORT'),
#
#     }
#
# }

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.mysql"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "init_command": "SET SESSION wait_timeout=28800",
        },
        "CONN_MAX_AGE": 3600,  # Keep connections open for an hour
    }
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=99999),  # Effectively unlimited
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # Set the refresh token lifetime
}


RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_SECRET_KEY = os.getenv("RAZORPAY_SECRET_KEY")

DEBUG = True

import os

MEDIA_URL = "/media/"  # URL to access media files
MEDIA_ROOT = os.path.join(BASE_DIR, "media")  # Directory to store uploaded media files

import os

# Storage settings for Backblaze B2
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
#
# AWS_ACCESS_KEY_ID = os.getenv("B2_ACCOUNT_ID")
# AWS_SECRET_ACCESS_KEY = os.getenv("B2_APPLICATION_KEY")
# AWS_STORAGE_BUCKET_NAME = os.getenv("B2_BUCKET_NAME")
# AWS_S3_ENDPOINT_URL = f"https://{os.getenv('B2_ENDPOINT')}"  # Uses your ENV variable
# AWS_S3_ADDRESSING_STYLE = "virtual"  # Required for Backblaze
# AWS_QUERYSTRING_AUTH = False  # Makes files publicly accessible

# Optional: Default ACL to private or public-read
# AWS_DEFAULT_ACL = "public-read"
import os

AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "ap-south-1")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")

INSTALLED_APPS += ["storages"]  # Ensure django-storages is installed
