# Generated by Django 5.1.1 on 2024-11-18 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_number', models.IntegerField(default=None)),
                ('pattern_name', models.CharField(max_length=100, unique=True)),
                ('pulse_display', models.URLField()),
                ('pulse_explanation', models.TextField()),
                ('yin_yang_url', models.URLField()),
                ('yin_yang_description', models.TextField()),
                ('organ_pattern_url', models.TextField(max_length=200)),
                ('organ_pattern_description', models.TextField()),
                ('image_url', models.TextField(max_length=200)),
            ],
        ),

    ]
