# Generated by Django 5.1.1 on 2024-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='organ_pattern_description',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='organ_pattern_url',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='pulse_display',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='pulse_explanation',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='yin_yang_description',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='yin_yang_url',
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01T00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_explanation_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_explanation_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='energy_variation_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='energy_variation_food_life',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='energy_variation_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='energy_variation_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='energy_variation_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='five_elements_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='meridian_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='meridian_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='nature_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='nature_explanation_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='nature_explanation_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_1_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_1_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_2_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_2_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_3_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_3_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_4_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_1_point_4_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_1_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_1_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_2_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_2_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_3_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_3_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_4_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_pattern_2_point_4_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='pulse_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='pulse_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_1_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_1_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_2_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_2_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_3_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_3_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_4_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_4_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_5_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_5_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_7_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_7_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_8_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_8_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='yin_yang_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='yin_yang_explanation_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='yin_yang_explanation_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticresource',
            name='pattern_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosticresource',
            name='pattern_number',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='diagnosticresource',
            table='diagnosis_report_data',
        ),

    ]
