# Generated by Django 5.1.1 on 2024-11-30 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patientsmodel_family_member'),
        ('pulse_payments', '0007_alter_servicetransactiondetails_service'),
        ('pulse_service', '0002_alter_pulsedata_user'),
        ('report_service', '0003_reporthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisReportHistory',
            fields=[
                ('report_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('primary', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary', models.CharField(blank=True, max_length=100, null=True)),
                ('tertiary', models.CharField(blank=True, max_length=100, null=True)),
                ('quaternary', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_histories', to='pulse_service.pulsedataobservations')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientsmodel')),
                ('pulse_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_histories', to='pulse_service.pulsedata')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnosis_report_history',
            },
        ),
        migrations.CreateModel(
            name='TreatmentReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_reports', to='report_service.diagnosisreporthistory')),
                ('service_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_histories', to='pulse_payments.service')),
            ],
            options={
                'db_table': 'treatment_report',
            },
        ),
        migrations.DeleteModel(
            name='ReportHistory',
        ),
    ]
