# Generated by Django 5.1.1 on 2024-11-30 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patientsmodel_family_member'),
        ('pulse_service', '0002_alter_pulsedata_user'),
        ('report_service', '0004_diagnosisreporthistory_treatmentreporthistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='observation_id',
            field=models.ForeignKey(blank=True, db_column='observation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_histories', to='pulse_service.pulsedataobservations'),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='patient_id',
            field=models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientsmodel'),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='pulse_id',
            field=models.ForeignKey(db_column='pulse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_histories', to='pulse_service.pulsedata'),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='report_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
