# Generated by Django 5.1.1 on 2024-11-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0005_alter_diagnosisreporthistory_observation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentreporthistory',
            old_name='service_name',
            new_name='service_id',
        ),
        migrations.RemoveField(
            model_name='treatmentreporthistory',
            name='treatment_name',
        ),
    ]
