# Generated by Django 5.1.1 on 2024-11-30 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_payments', '0007_alter_servicetransactiondetails_service'),
        ('report_service', '0006_rename_service_name_treatmentreporthistory_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentreporthistory',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_histories', to='pulse_payments.service'),
        ),
    ]
