# Generated by Django 5.1.1 on 2024-12-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0007_alter_treatmentreporthistory_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_6_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_6_image_2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
