# Generated by Django 5.1.1 on 2024-12-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0008_diagnosticresource_quick_solutions_6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='observation_id',
        ),
    ]
