# Generated by Django 5.1.1 on 2024-12-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0009_remove_diagnosisreporthistory_observation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=20)),
                ('pattern_number', models.IntegerField()),
                ('pulse_image', models.URLField(blank=True, null=True)),
                ('pulse_analysis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diagnosis_report_table',
            },
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'treatment_type',
            },
        ),
        migrations.CreateModel(
            name='Auricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.TextField(blank=True, help_text='Points for auricular treatment.', null=True)),
                ('base_image', models.URLField(blank=True, help_text='URL of the base image.', null=True)),
                ('note_1', models.TextField(blank=True, null=True)),
                ('note_2', models.TextField(blank=True, null=True)),
                ('note_3', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auriculars', to='report_service.diagnosisreport')),
            ],
            options={
                'db_table': 'auricular',
            },
        ),
        migrations.CreateModel(
            name='TreatmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.TextField(blank=True, help_text='Points related to the treatment.', null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('image_1', models.URLField(blank=True, null=True)),
                ('image_2', models.URLField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_details', to='report_service.diagnosisreport')),
                ('treatment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_details', to='report_service.treatmenttype')),
            ],
            options={
                'db_table': 'treatment_detail',
            },
        ),
    ]
