# Generated by Django 5.1.1 on 2024-12-21 13:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0010_diagnosisreport_treatmenttype_auricular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auricular',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 21, 13, 8, 11, 798589, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auricular',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auriculars_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auricular',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auricular',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auriculars_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_reports_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_reports_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmentdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 21, 13, 9, 4, 780073, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentdetail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_details_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmentdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='treatmentdetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_details_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 21, 13, 9, 15, 92049, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_types_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='treatmenttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_types_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
