# Generated by Django 5.1.1 on 2024-12-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0011_auricular_created_at_auricular_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentdetail',
            name='treatment_type',
        ),
        migrations.AlterField(
            model_name='auricular',
            name='points',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], help_text='Select points for auricular treatment.', max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='TreatmentType',
        ),
    ]
