# Generated by Django 5.1.1 on 2024-12-22 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0012_remove_treatmentdetail_treatment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricular',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auriculars', to='report_service.diagnosticresource'),
        ),
    ]
