# Generated by Django 5.1.1 on 2024-12-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0013_alter_auricular_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auricular',
            old_name='report',
            new_name='auricular_report',
        ),
        migrations.RenameField(
            model_name='auricular',
            old_name='points',
            new_name='frequent_points',
        ),
    ]
