# Generated by Django 5.1.1 on 2024-12-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0014_rename_report_auricular_auricular_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auricular',
            name='note_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auricular',
            name='rare_points',
            field=models.CharField(blank=True, choices=[('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5')], help_text='Select rare points for auricular treatment.', max_length=2, null=True),
        ),
    ]
