# Generated by Django 5.1.1 on 2024-12-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0015_auricular_note_4_auricular_rare_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentdetail',
            name='report',
        ),
        migrations.RemoveField(
            model_name='treatmentdetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='treatmentdetail',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='DiagnosisReport',
        ),
        migrations.DeleteModel(
            name='TreatmentDetail',
        ),
    ]
