# Generated by Django 5.1.1 on 2024-12-22 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0016_remove_treatmentdetail_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auricular_report', models.CharField(blank=True, choices=[('protocol1', 'Protocol 1'), ('protocol2', 'Protocol 2'), ('protocol3', 'Protocol 3'), ('protocol4', 'Protocol 4')], help_text='Select protocols for auricular reports.', max_length=50, null=True)),
                ('color_therapy', models.CharField(blank=True, choices=[('protocol1', 'Protocol 1'), ('protocol2', 'Protocol 2'), ('protocol3', 'Protocol 3'), ('protocol4', 'Protocol 4')], help_text='Select protocols for color therapy.', max_length=50, null=True)),
                ('seed_therapy', models.CharField(blank=True, choices=[('protocol1', 'Protocol 1'), ('protocol2', 'Protocol 2'), ('protocol3', 'Protocol 3'), ('protocol4', 'Protocol 4')], help_text='Select protocols for seed therapy.', max_length=50, null=True)),
                ('single_point_report', models.CharField(blank=True, choices=[('protocol1', 'Protocol 1'), ('protocol2', 'Protocol 2'), ('protocol3', 'Protocol 3'), ('protocol4', 'Protocol 4')], help_text='Select protocols for single point reports.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_selectors_created_by', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='report_selectors', to='report_service.diagnosticresource')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_selectors_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_selector',
            },
        ),
        migrations.DeleteModel(
            name='Auricular',
        ),
    ]
