# Generated by Django 5.1.1 on 2024-12-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0017_reportselector_delete_auricular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportselector',
            name='auricular_report',
            field=models.JSONField(blank=True, help_text='Select multiple protocols for auricular reports.', null=True),
        ),
        migrations.AlterField(
            model_name='reportselector',
            name='color_therapy',
            field=models.JSONField(blank=True, help_text='Select multiple protocols for color therapy.', null=True),
        ),
        migrations.AlterField(
            model_name='reportselector',
            name='seed_therapy',
            field=models.JSONField(blank=True, help_text='Select multiple protocols for seed therapy.', null=True),
        ),
        migrations.AlterField(
            model_name='reportselector',
            name='single_point_report',
            field=models.JSONField(blank=True, help_text='Select multiple protocols for single point reports.', null=True),
        ),
    ]
