# Generated by Django 5.1.1 on 2024-12-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0018_alter_reportselector_auricular_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportselector',
            name='auricular_report',
            field=models.CharField(blank=True, default='', help_text='Select protocols for auricular reports (multiple selections allowed).', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportselector',
            name='color_therapy',
            field=models.CharField(blank=True, default='', help_text='Select protocols for color therapy (multiple selections allowed).', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportselector',
            name='seed_therapy',
            field=models.CharField(blank=True, default='', help_text='Select protocols for seed therapy (multiple selections allowed).', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportselector',
            name='single_point_report',
            field=models.CharField(blank=True, default='', help_text='Select protocols for single point reports (multiple selections allowed).', max_length=255),
            preserve_default=False,
        ),
    ]
