# Generated by Django 5.1.1 on 2024-12-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0019_alter_reportselector_auricular_report_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportselector',
            old_name='auricular_report',
            new_name='auricular_protocol',
        ),
        migrations.RenameField(
            model_name='reportselector',
            old_name='color_therapy',
            new_name='color_therapy_protocol',
        ),
        migrations.RenameField(
            model_name='reportselector',
            old_name='seed_therapy',
            new_name='seed_therapy_protocol',
        ),
        migrations.RenameField(
            model_name='reportselector',
            old_name='single_point_report',
            new_name='single_point_protocol',
        ),
        migrations.AddField(
            model_name='reportselector',
            name='acupressure_protocol',
            field=models.CharField(blank=True, help_text='Select protocols for acupressure (multiple selections allowed).', max_length=255),
        ),
        migrations.AddField(
            model_name='reportselector',
            name='mudra_protocol',
            field=models.CharField(blank=True, help_text='Select protocols for mudra (multiple selections allowed).', max_length=255),
        ),
        migrations.AddField(
            model_name='reportselector',
            name='pranayama_protocol',
            field=models.CharField(blank=True, help_text='Select protocols for pranayama (multiple selections allowed).', max_length=255),
        ),
        migrations.AddField(
            model_name='reportselector',
            name='yoga_protocol',
            field=models.CharField(blank=True, help_text='Select protocols for yoga (multiple selections allowed).', max_length=255),
        ),
    ]
