# Generated by Django 5.1.1 on 2024-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0020_rename_auricular_report_reportselector_auricular_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
