# Generated by Django 5.1.1 on 2024-12-28 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0021_diagnosisreporthistory_treatment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuricularProtocolBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_1', models.CharField(blank=True, choices=[('sp 1', 'sp 1'), ('sp 2', 'sp 2'), ('sp 3', 'sp 3')], help_text='Select multiple options for Protocol 1', max_length=255)),
                ('protocol_2', models.CharField(blank=True, choices=[('sp 4', 'sp 4'), ('sp 5', 'sp 5'), ('sp 6', 'sp 6')], help_text='Select multiple options for Protocol 2', max_length=255)),
                ('protocol_3', models.CharField(blank=True, choices=[('sp 7', 'sp 7'), ('sp 8', 'sp 8'), ('sp 9', 'sp 9')], help_text='Select multiple options for Protocol 3', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auricular_protocols_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auricular_protocols_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
