# Generated by Django 5.1.1 on 2024-12-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0022_auricularprotocolbank'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auricularprotocolbank',
            table='auricularprotocolbank',
        ),
    ]
