# Generated by Django 5.1.1 on 2024-12-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0023_alter_auricularprotocolbank_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='protocol_1',
            field=models.CharField(blank=True, choices=[('sp 1', 'sp 1'), ('sp 2', 'sp 2'), ('sp 3', 'sp 3')], help_text='Select protocols for Protocol 1 (multiple selections allowed).', max_length=255),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='protocol_2',
            field=models.CharField(blank=True, choices=[('sp 4', 'sp 4'), ('sp 5', 'sp 5'), ('sp 6', 'sp 6')], help_text='Select protocols for Protocol 2 (multiple selections allowed).', max_length=255),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='protocol_3',
            field=models.CharField(blank=True, choices=[('sp 7', 'sp 7'), ('sp 8', 'sp 8'), ('sp 9', 'sp 9')], help_text='Select protocols for Protocol 3 (multiple selections allowed).', max_length=255),
        ),
        migrations.AlterModelTable(
            name='auricularprotocolbank',
            table=None,
        ),
    ]
