# Generated by Django 5.1.1 on 2024-12-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0024_alter_auricularprotocolbank_protocol_1_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auricularprotocolbank',
            table='auricularprotocolbank',
        ),
    ]
