# Generated by Django 5.1.1 on 2024-12-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0025_alter_auricularprotocolbank_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='protocol_1',
            field=models.TextField(blank=True, help_text='Select multiple protocols for Protocol 1 (comma-separated values).'),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='protocol_2',
            field=models.TextField(blank=True, help_text='Select multiple protocols for Protocol 2 (comma-separated values).'),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='protocol_3',
            field=models.TextField(blank=True, help_text='Select multiple protocols for Protocol 3 (comma-separated values).'),
        ),
    ]
