# Generated by Django 5.1.1 on 2024-12-29 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0026_alter_auricularprotocolbank_protocol_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='report',
            field=models.ForeignKey(default=1, help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='auricular_protocol_reports', to='report_service.diagnosticresource'),
            preserve_default=False,
        ),
    ]
