# Generated by Django 5.1.1 on 2024-12-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0027_auricularprotocolbank_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auricularprotocolbank',
            name='report',
        ),
    ]
