# Generated by Django 5.1.1 on 2024-12-29 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0028_remove_auricularprotocolbank_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auricularprotocolbank',
            table='auricular_protocol_bank',
        ),
        migrations.CreateModel(
            name='AuricularReportSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auricular_reports_created_by', to=settings.AUTH_USER_MODEL)),
                ('protocols', models.ManyToManyField(blank=True, help_text='Select multiple protocols from Auricular Protocol Bank.', related_name='auricular_reports', to='report_service.auricularprotocolbank')),
                ('report', models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='auricular_report_systems', to='report_service.diagnosticresource')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auricular_reports_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auricular_report_system',
            },
        ),
    ]
