# Generated by Django 5.1.1 on 2024-12-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0029_alter_auricularprotocolbank_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auricularreportsystem',
            name='protocols',
        ),
        migrations.AlterModelTable(
            name='auricularreportsystem',
            table=None,
        ),
        migrations.AddField(
            model_name='auricularreportsystem',
            name='protocols',
            field=models.CharField(blank=True, help_text='Select protocols from Auricular Protocol Bank.', max_length=255),
        ),
    ]
