# Generated by Django 5.1.1 on 2024-12-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0030_remove_auricularreportsystem_protocols_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auricularreportsystem',
            table='auricular_report_system',
        ),
    ]
