# Generated by Django 5.1.1 on 2024-12-29 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0031_alter_auricularreportsystem_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MudraProtocolBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_1', models.CharField(blank=True, choices=[('Vayu Mudra', 'Vayu Mudra'), ('Jala Mudra', 'Jala Mudra'), ('Prana Mudra', 'Prana Mudra')], help_text='Select a value for Protocol 1', max_length=255)),
                ('protocol_2', models.CharField(blank=True, choices=[('Vayu Mudra', 'Vayu Mudra'), ('Jala Mudra', 'Jala Mudra'), ('Prana Mudra', 'Prana Mudra')], help_text='Select a value for Protocol 2', max_length=255)),
                ('protocol_3', models.CharField(blank=True, choices=[('Vayu Mudra', 'Vayu Mudra'), ('Jala Mudra', 'Jala Mudra'), ('Prana Mudra', 'Prana Mudra')], help_text='Select a value for Protocol 3', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mudra_protocols_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mudra_protocols_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mudra_protocol_bank',
            },
        ),
    ]
