# Generated by Django 5.1.1 on 2024-12-29 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0032_mudraprotocolbank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MudraReportSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocols', models.CharField(blank=True, help_text='Select protocols from Mudra Protocol Bank.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mudra_reports_created_by', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='mudra_report_systems', to='report_service.diagnosticresource')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mudra_reports_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mudra_report_system',
            },
        ),
    ]
