# Generated by Django 5.1.1 on 2024-12-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0033_mudrareportsystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mudraprotocolbank',
            name='protocol_1',
        ),
        migrations.RemoveField(
            model_name='mudraprotocolbank',
            name='protocol_2',
        ),
        migrations.RemoveField(
            model_name='mudraprotocolbank',
            name='protocol_3',
        ),
        migrations.RemoveField(
            model_name='mudrareportsystem',
            name='protocols',
        ),
        migrations.AddField(
            model_name='mudraprotocolbank',
            name='protocol',
            field=models.CharField(blank=True, choices=[('Vayu Mudra', 'Vayu Mudra'), ('Jala Mudra', 'Jala Mudra'), ('Prana Mudra', 'Prana Mudra')], help_text='Select a Mudra Protocol', max_length=255),
        ),
        migrations.AddField(
            model_name='mudrareportsystem',
            name='protocol',
            field=models.ForeignKey(default=1, help_text='Select a Mudra Protocol from the Mudra Protocol Bank.', on_delete=django.db.models.deletion.CASCADE, related_name='mudra_report_systems', to='report_service.mudraprotocolbank'),
            preserve_default=False,
        ),
    ]
