# Generated by Django 5.1.1 on 2024-12-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0034_remove_mudraprotocolbank_protocol_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mudrareportsystem',
            name='protocol',
        ),
        migrations.AddField(
            model_name='mudrareportsystem',
            name='protocols',
            field=models.ManyToManyField(help_text='Select multiple Mudra Protocols from the Mudra Protocol Bank.', related_name='mudra_report_systems', to='report_service.mudraprotocolbank'),
        ),
    ]
