# Generated by Django 5.1.1 on 2024-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0035_remove_mudrareportsystem_protocol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auricularprotocolbank',
            name='protocol_1',
        ),
        migrations.RemoveField(
            model_name='auricularprotocolbank',
            name='protocol_2',
        ),
        migrations.RemoveField(
            model_name='auricularprotocolbank',
            name='protocol_3',
        ),
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='protocol',
            field=models.CharField(choices=[('SP-1', 'SP-1'), ('SP-2', 'SP-2'), ('SP-3', 'SP-3'), ('SP-4', 'SP-4'), ('SP-5', 'SP-5'), ('SP-6', 'SP-6'), ('SP-7', 'SP-7'), ('SP-8', 'SP-8'), ('SP-9', 'SP-9')], default=1, help_text='Select a protocol from the available choices.', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='auricularreportsystem',
            name='protocols',
        ),
        migrations.AddField(
            model_name='auricularreportsystem',
            name='protocols',
            field=models.ManyToManyField(help_text='Select multiple Auricular Protocols from the Auricular Protocol Bank.', related_name='auricular_report_systems', to='report_service.auricularprotocolbank'),
        ),
    ]
