# Generated by Django 5.1.1 on 2024-12-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0036_remove_auricularprotocolbank_protocol_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='protocol',
            field=models.TextField(blank=True, help_text='Select multiple protocols (comma-separated values will be stored).'),
        ),
    ]
