# Generated by Django 5.1.1 on 2024-12-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0037_alter_auricularprotocolbank_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='protocol',
            field=models.TextField(blank=True, help_text='Select multiple protocols for Protocol 1 (comma-separated values).'),
        ),
    ]
