# Generated by Django 5.1.1 on 2024-12-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0038_alter_auricularprotocolbank_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auricularreportsystem',
            name='protocols',
        ),
        migrations.AddField(
            model_name='auricularreportsystem',
            name='protocols',
            field=models.TextField(blank=True, help_text='Select multiple protocols as comma-separated values.'),
        ),
    ]
