# Generated by Django 5.1.1 on 2024-12-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0039_remove_auricularreportsystem_protocols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricularreportsystem',
            name='protocols',
            field=models.TextField(blank=True, help_text='Select multiple protocols as comma-separated values (stored as IDs).'),
        ),
    ]
