# Generated by Django 5.1.1 on 2024-12-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0040_alter_auricularreportsystem_protocols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mudrareportsystem',
            name='protocols',
        ),
        migrations.AddField(
            model_name='mudrareportsystem',
            name='protocols',
            field=models.TextField(blank=True, help_text='Select multiple protocols as comma-separated values (stored as IDs).'),
        ),
    ]
