# Generated by Django 5.1.1 on 2024-12-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0041_remove_mudrareportsystem_protocols_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auricularreportsystem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='auricularreportsystem',
            name='report',
        ),
        migrations.RemoveField(
            model_name='auricularreportsystem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='mudraprotocolbank',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mudraprotocolbank',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='mudrareportsystem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mudrareportsystem',
            name='report',
        ),
        migrations.RemoveField(
            model_name='mudrareportsystem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reportselector',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportselector',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportselector',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AuricularProtocolBank',
        ),
        migrations.DeleteModel(
            name='AuricularReportSystem',
        ),
        migrations.DeleteModel(
            name='MudraProtocolBank',
        ),
        migrations.DeleteModel(
            name='MudraReportSystem',
        ),
        migrations.DeleteModel(
            name='ReportSelector',
        ),
    ]
