# Generated by Django 5.1.1 on 2024-12-31 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0042_remove_auricularreportsystem_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='report_pattern_type',
            field=models.ForeignKey(blank=True, db_column='report_pattern_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_reports', to='report_service.diagnosticresource'),
        ),
    ]
