# Generated by Django 5.1.1 on 2025-01-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0043_diagnosisreporthistory_report_pattern_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='auricular_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='colour_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='mudra_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='pranayama_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='seed_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='single_point_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='yoga_treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
