# Generated by Django 5.1.1 on 2025-01-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0044_diagnosisreporthistory_auricular_treatment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('pattern_number', models.AutoField(primary_key=True, serialize=False)),
                ('pattern_name', models.CharField(max_length=255)),
                ('primary', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary', models.CharField(blank=True, max_length=255, null=True)),
                ('tertiary', models.CharField(blank=True, max_length=255, null=True)),
                ('quaternary', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
