# Generated by Django 5.1.1 on 2025-01-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0045_patterns'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patterns',
            table='patterns',
        ),
    ]
