# Generated by Django 5.1.1 on 2025-01-01 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0046_alter_patterns_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='report_pattern_type',
            field=models.ForeignKey(blank=True, db_column='report_pattern_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_reports', to='report_service.patterns'),
        ),
    ]
