# Generated by Django 5.1.1 on 2025-01-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0047_alter_diagnosisreporthistory_report_pattern_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patterns',
            name='pattern_name',
        ),
        migrations.AlterField(
            model_name='patterns',
            name='pattern_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
