# Generated by Django 5.1.1 on 2025-01-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0048_remove_patterns_pattern_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterns',
            name='pattern_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patterns',
            name='pattern_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
