# Generated by Django 5.1.1 on 2025-01-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0049_patterns_pattern_name_alter_patterns_pattern_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patterns',
            old_name='pattern_number',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='patterns',
            name='pattern_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
