# Generated by Django 5.1.1 on 2025-01-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0052_alter_patterns_pattern_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterns',
            name='primary',
            field=models.CharField(blank=True, choices=[('wind', 'Wind'), ('heat', 'Heat'), ('cold', 'Cold'), ('dry', 'Dry'), ('humid', 'Humid')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patterns',
            name='quaternary',
            field=models.CharField(blank=True, choices=[('wind', 'Wind'), ('heat', 'Heat'), ('cold', 'Cold'), ('dry', 'Dry'), ('humid', 'Humid')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patterns',
            name='secondary',
            field=models.CharField(blank=True, choices=[('wind', 'Wind'), ('heat', 'Heat'), ('cold', 'Cold'), ('dry', 'Dry'), ('humid', 'Humid')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patterns',
            name='tertiary',
            field=models.CharField(blank=True, choices=[('wind', 'Wind'), ('heat', 'Heat'), ('cold', 'Cold'), ('dry', 'Dry'), ('humid', 'Humid')], max_length=255, null=True),
        ),
    ]
