# Generated by Django 5.1.1 on 2025-01-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0053_alter_patterns_primary_alter_patterns_quaternary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patterns',
            old_name='id',
            new_name='pattern_id',
        ),
    ]
