# Generated by Django 5.1.1 on 2025-02-10 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0055_questionbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.ImageField(upload_to='diagnostic/images/mobile/')),
                ('pdf', models.ImageField(upload_to='diagnostic/images/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticResource1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_number', models.CharField(max_length=50, unique=True)),
                ('pattern_name', models.CharField(max_length=255)),
                ('pulse_explanation', models.TextField()),
                ('vpk_values', models.JSONField()),
                ('vpk_text', models.TextField()),
                ('yin_yang', models.CharField(choices=[('liver-yin', 'Liver-Yin'), ('liver-yang', 'Liver-Yang'), ('heart-yin', 'Heart-Yin'), ('heart-yang', 'Heart-Yang'), ('sp-yin', 'SP-Yin'), ('sp-yang', 'SP-Yang'), ('lr-yin', 'Lr-Yin'), ('lr-yang', 'Lr-Yang'), ('kd-yin', 'Kd-Yin'), ('kd-yang', 'Kd-Yang')], max_length=20, unique=True, verbose_name='Yin-Yang Organ')),
                ('organ_relation_text1', models.TextField()),
                ('organ_relation_text2', models.TextField()),
                ('organ_relation_text3', models.TextField()),
                ('organ_relation_text4', models.TextField()),
                ('nature_correlation_text', models.TextField()),
                ('thought_pattern_text', models.TextField()),
                ('ai_prediction_text1', models.TextField()),
                ('ai_prediction_text2', models.TextField()),
                ('ai_prediction_text3', models.TextField()),
                ('ai_prediction_text4', models.TextField()),
                ('cfp_value', models.FloatField()),
                ('cfp_text', models.TextField()),
                ('ai_prediction_image1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prediction_image1', to='report_service.imageresource')),
                ('ai_prediction_image2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prediction_image2', to='report_service.imageresource')),
                ('body_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_image', to='report_service.imageresource')),
                ('cfp_icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cfp_icon', to='report_service.imageresource')),
                ('nature_correlation_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nature_correlation_image', to='report_service.imageresource')),
                ('organ_relation_icon1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organ_icon1', to='report_service.imageresource')),
                ('organ_relation_icon2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organ_icon2', to='report_service.imageresource')),
                ('organ_relation_icon3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organ_icon3', to='report_service.imageresource')),
                ('organ_relation_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organ_relationship_image', to='report_service.imageresource')),
                ('pulse_explanation_icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_explanation_icon', to='report_service.imageresource')),
                ('pulse_picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_picture', to='report_service.imageresource')),
                ('thought_pattern_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thought_pattern_image', to='report_service.imageresource')),
                ('vpk_icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpk_icon', to='report_service.imageresource')),
            ],
        ),
        migrations.CreateModel(
            name='QuickSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('diagnostic_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_solutions', to='report_service.diagnosticresource1')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_solution_image', to='report_service.imageresource')),
            ],
        ),
    ]
