# Generated by Django 5.1.1 on 2025-02-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0056_imageresource_diagnosticresource1_quicksolution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosticResource',
        ),
        migrations.AlterModelTable(
            name='diagnosticresource1',
            table='diagnosis_report_data1',
        ),
    ]
