# Generated by Django 5.1.1 on 2025-02-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0057_delete_diagnosticresource_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiagnosticResource1',
            new_name='DiagnosticResource',
        ),
    ]
