# Generated by Django 5.1.1 on 2025-02-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0058_rename_diagnosticresource1_diagnosticresource'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diagnosticresource',
            table='diagnostic_resource',
        ),
    ]
