# Generated by Django 5.1.1 on 2025-02-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0059_alter_diagnosticresource_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='organ_relation_icon2',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='pulse_explanation_icon',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='organ_relation_icon1',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='organ_relation_icon3',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='organ_relation_image',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='ai_prediction_image2',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='pulse_picture',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='nature_correlation_image',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='vpk_icon',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='ai_prediction_image1',
        ),
        migrations.RemoveField(
            model_name='quicksolution',
            name='image',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='thought_pattern_image',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='cfp_icon',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='body_image',
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='ai_prediction_image1_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='ai_prediction_image1_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='ai_prediction_image2_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='ai_prediction_image2_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='body_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/body_images/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='body_image_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/body_images/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='cfp_icon_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/cfp_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='cfp_icon_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/cfp_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='heart_rate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='nature_correlation_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/nature_correlation/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='nature_correlation_image_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/nature_correlation/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_relation_icon1_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_relation_icon1_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_relation_icon2_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_relation_icon2_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_relation_icon3_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_relation_icon3_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_relation_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_relationship/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='organ_relation_image_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_relationship/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='pulse_explanation_icon_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/pulse_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='pulse_explanation_icon_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/pulse_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='pulse_picture_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/pulse_pictures/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='pulse_picture_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/pulse_pictures/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='thought_pattern_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/thought_patterns/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='thought_pattern_image_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/thought_patterns/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='vpk_icon_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/vpk_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='vpk_icon_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/vpk_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/quick_solutions/mobile/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='image_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic/quick_solutions/pdf/'),
        ),
        migrations.DeleteModel(
            name='ImageResource',
        ),
    ]
