# Generated by Django 5.1.1 on 2025-02-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0060_remove_diagnosticresource_organ_relation_icon2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticresource',
            name='yin_yang',
            field=models.JSONField(default={'heart_yang': '', 'heart_yin': '', 'kd_yang': '', 'kd_yin': '', 'liver_yang': '', 'liver_yin': '', 'lr_yang': '', 'lr_yin': '', 'sp_yang': '', 'sp_yin': ''}),
        ),
    ]
