# Generated by Django 5.1.1 on 2025-02-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0061_alter_diagnosticresource_yin_yang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticresource',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
