# Generated by Django 5.1.1 on 2025-02-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0062_alter_diagnosticresource_heart_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quicksolution',
            old_name='image_mobile',
            new_name='mobile_image',
        ),
        migrations.RenameField(
            model_name='quicksolution',
            old_name='image_pdf',
            new_name='pdf_image',
        ),
    ]
