# Generated by Django 5.1.1 on 2025-02-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0063_rename_image_mobile_quicksolution_mobile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResource1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_number', models.CharField(max_length=50, unique=True)),
                ('pattern_name', models.CharField(max_length=255)),
                ('pulse_pdf_image', models.ImageField(blank=True, null=True, upload_to='diagnostic/pulse_images/pdf/')),
                ('pulse_mobile_image', models.ImageField(blank=True, null=True, upload_to='diagnostic/pulse_images/mobile/')),
                ('pulse_explanation', models.TextField()),
                ('pulse_pdf_icon', models.ImageField(blank=True, null=True, upload_to='diagnostic/pulse_icons/pdf/')),
                ('pulse_mobile_icon', models.ImageField(blank=True, null=True, upload_to='diagnostic/pulse_icons/mobile/')),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('tridosha_pdf_graph', models.ImageField(blank=True, null=True, upload_to='diagnostic/tridosha_graph/pdf/')),
                ('tridosha_mobile_graph', models.ImageField(blank=True, null=True, upload_to='diagnostic/tridosha_graph/pdf/')),
                ('tridosha_values', models.JSONField()),
                ('tridosha_text', models.TextField()),
                ('tridosha_pdf_icon', models.ImageField(blank=True, null=True, upload_to='diagnostic/tridosha_icons/pdf/')),
                ('tridosha_mobile_icon', models.ImageField(blank=True, null=True, upload_to='diagnostic/tridosha_icons/mobile/')),
                ('yin_yang_pdf_graph', models.ImageField(blank=True, null=True, upload_to='diagnostic/yin_yang_graph/pdf/')),
                ('yin_yang_mobile_graph', models.ImageField(blank=True, null=True, upload_to='diagnostic/tridosha_icons/mobile/')),
                ('yin_yang', models.JSONField(default={'heart_yang': '', 'heart_yin': '', 'kd_yang': '', 'kd_yin': '', 'liver_yang': '', 'liver_yin': '', 'lr_yang': '', 'lr_yin': '', 'sp_yang': '', 'sp_yin': ''})),
                ('organ_rel_pdf_image', models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_rel/pdf/')),
                ('organ_rel_mobile_image', models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_rel/mobile/')),
                ('organ_rel_text1', models.TextField()),
                ('organ_rel_text2', models.TextField()),
                ('organ_rel_text3', models.TextField()),
                ('organ_rel_text4', models.TextField()),
                ('organ_rel_pdf_icon1', models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/pdf/')),
                ('organ_rel_mobile_icon1', models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/mobile/')),
                ('organ_rel_pdf_icon2', models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/pdf/')),
                ('organ_rel_mobile_icon2', models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/mobile/')),
                ('organ_rel_pdf_icon3', models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/pdf/')),
                ('organ_rel_mobile_icon3', models.ImageField(blank=True, null=True, upload_to='diagnostic/organ_images/mobile/')),
                ('nature_correlation_text', models.TextField()),
                ('nature_correlation_pdf_image', models.ImageField(blank=True, null=True, upload_to='diagnostic/nature_correlation/pdf/')),
                ('nature_correlation_mobile_image', models.ImageField(blank=True, null=True, upload_to='diagnostic/nature_correlation/mobile/')),
                ('thought_pattern_text', models.TextField()),
                ('thought_pattern_pdf_image', models.ImageField(blank=True, null=True, upload_to='diagnostic/thought_patterns/pdf/')),
                ('thought_pattern_mobile_image', models.ImageField(blank=True, null=True, upload_to='diagnostic/thought_patterns/mobile/')),
                ('fm_pdf_graph', models.ImageField(blank=True, null=True, upload_to='diagnostic/fm_graph/pdf/')),
                ('fm_mobile_graph', models.ImageField(blank=True, null=True, upload_to='diagnostic/fm_graph/mobile/')),
                ('fm_values', models.JSONField(blank=True, null=True)),
                ('fm_text', models.TextField()),
                ('fm_pdf_icon', models.ImageField(blank=True, null=True, upload_to='diagnostic/fm_icons/pdf/')),
                ('fm_mobile_icon', models.ImageField(blank=True, null=True, upload_to='diagnostic/fm_icons/mobile/')),
                ('ai_prediction_text1', models.TextField()),
                ('ai_prediction_text2', models.TextField()),
                ('ai_prediction_text3', models.TextField()),
                ('ai_prediction_text4', models.TextField()),
                ('ai_prediction_pdf_icon1', models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/pdf/')),
                ('ai_prediction_mobile_icon1', models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/mobile/')),
                ('ai_prediction_pdf_icon2', models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/pdf/')),
                ('ai_prediction_mobile_icon2', models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/mobile/')),
                ('ai_prediction_pdf_icon3', models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/pdf/')),
                ('ai_prediction_mobile_icon3', models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/mobile/')),
                ('ai_prediction_pdf_icon4', models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/pdf/')),
                ('ai_prediction_mobile_icon4', models.ImageField(blank=True, null=True, upload_to='diagnostic/ai_predictions/mobile/')),
                ('body_pdf_image', models.ImageField(blank=True, null=True, upload_to='diagnostic/body_images/pdf/')),
                ('body_mobile_image', models.ImageField(blank=True, null=True, upload_to='diagnostic/body_images/mobile/')),
            ],
            options={
                'db_table': 'diagnostic_resource1',
            },
        ),
    ]
