# Generated by Django 5.1.1 on 2025-02-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0064_diagnosticresource1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksolution',
            name='diagnostic_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_solutions', to='report_service.diagnosticresource1'),
        ),
        migrations.DeleteModel(
            name='DiagnosticResource',
        ),
    ]
