# Generated by Django 5.1.1 on 2025-02-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0065_alter_quicksolution_diagnostic_resource_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiagnosticResource1',
            new_name='DiagnosticResource',
        ),
        migrations.AlterModelTable(
            name='diagnosticresource',
            table='diagnostic_resource',
        ),
    ]
