# Generated by Django 5.1.1 on 2025-02-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0067_alter_diagnosticresource_ai_prediction_mobile_icon1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='cold_AC_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='cold_BC_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='dryness_delay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='dryness_spike_F_A11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='heat_CE_ampli',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='humid_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='humid_ratio_cold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='humidity_C1D_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='humidity_C1D_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='humidity_CD_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='quinary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='wind_AA1_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='wind_AA1_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='wind_angle',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
