# Generated by Django 5.1.1 on 2025-02-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0068_diagnosisreporthistory_cold_ac_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterns',
            name='quinary',
            field=models.CharField(blank=True, choices=[('wind', 'Wind'), ('heat', 'Heat'), ('cold', 'Cold'), ('dry', 'Dry'), ('humid', 'Humid')], max_length=255, null=True),
        ),
    ]
