# Generated by Django 5.1.1 on 2025-02-22 09:08

import report_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0069_patterns_quinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_mobile_image1',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/organ_images/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_pdf_image1',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/organ_images/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='quick_solutions_text1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quicksolution',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/mobile/'),
        ),
        migrations.AlterField(
            model_name='quicksolution',
            name='pdf_image',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/pdf/'),
        ),
    ]
