# Generated by Django 5.1.1 on 2025-02-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0070_diagnosticresource_quick_solutions_mobile_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='quick_solutions_mobile_image1',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='quick_solutions_pdf_image1',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='quick_solutions_text1',
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='heading',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
