# Generated by Django 5.1.1 on 2025-02-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0071_remove_diagnosticresource_quick_solutions_mobile_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='cold_AC_time',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='cold_BC_time',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='dryness_delay',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='dryness_spike_F_A11',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='heat_CE_ampli',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='humid_ratio',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='humid_ratio_cold',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='humidity_C1D_area',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='humidity_C1D_time',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='humidity_CD_time',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='wind_AA1_area',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='wind_AA1_time',
        ),
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='wind_angle',
        ),
    ]
