# Generated by Django 5.1.1 on 2025-02-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0072_remove_diagnosisreporthistory_cold_ac_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisreporthistory',
            name='treatment',
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='carbohydrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='cold_yang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='cold_yin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='dry_yang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='dry_yin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='heat_yang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='heat_yin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='humid_yang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='humid_yin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='kapha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='pitta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='vata',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='wind_yang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='wind_yin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
