# Generated by Django 5.1.1 on 2025-02-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0073_remove_diagnosisreporthistory_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='cold_yang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='cold_yin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='dry_yang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='dry_yin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='heat_yang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='heat_yin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='humid_yang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='humid_yin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='kapha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='pitta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='vata',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='wind_yang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='wind_yin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
