# Generated by Django 5.1.1 on 2025-02-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0074_alter_diagnosisreporthistory_cold_yang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='carbohydrate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='fat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='protein',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
