# Generated by Django 5.1.1 on 2025-02-28 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0075_alter_diagnosisreporthistory_carbohydrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('answers', models.JSONField(default=['Excellent', 'Good', 'Average', 'Poor'])),
            ],
            options={
                'db_table': 'question_model',
            },
        ),
        migrations.CreateModel(
            name='QuestionsSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'question_set',
            },
        ),
        migrations.CreateModel(
            name='QuestionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, help_text='Optional icon image for the question.', null=True, upload_to='question_icons/')),
                ('options', models.JSONField(help_text="List of available options, e.g. ['Yes', 'No']")),
                ('next_questions', models.JSONField(default=dict, help_text='Mapping of option to next question key, e.g. {"Yes": "q2", "No": "q3"}')),
                ('question', models.ForeignKey(help_text='Select a question from QuestionModel', on_delete=django.db.models.deletion.CASCADE, to='report_service.questionmodel')),
                ('questions_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='report_service.questionsset')),
            ],
            options={
                'db_table': 'question_link',
            },
        ),
    ]
