# Generated by Django 5.1.1 on 2025-02-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0076_questionmodel_questionsset_questionlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlink',
            name='options',
        ),
    ]
