# Generated by Django 5.1.1 on 2025-02-28 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0077_remove_questionlink_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlink',
            name='question',
            field=models.ForeignKey(help_text='Select a question from QuestionModel by its unique question_number', on_delete=django.db.models.deletion.CASCADE, to='report_service.questionmodel', to_field='question_number'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='question_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
