# Generated by Django 5.1.1 on 2025-03-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0079_alter_questionlink_question'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quicksolution',
            table='quick_solution',
        ),
    ]
