# Generated by Django 5.1.1 on 2025-03-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0080_alter_quicksolution_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quicksolution',
            old_name='mobile_image',
            new_name='mobile_image_1',
        ),
        migrations.RenameField(
            model_name='quicksolution',
            old_name='pdf_image',
            new_name='pdf_image_1',
        ),
        migrations.RenameField(
            model_name='quicksolution',
            old_name='text',
            new_name='text_1',
        ),
    ]
