# Generated by Django 5.1.1 on 2025-03-01 08:56

import report_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0081_rename_mobile_image_quicksolution_mobile_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksolution',
            name='mobile_image_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/mobile/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='mobile_image_3',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/mobile/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='mobile_image_4',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/mobile/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='mobile_image_5',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/mobile/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='mobile_image_6',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/mobile/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='mobile_image_7',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/mobile/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='mobile_image_8',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/mobile/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='pdf_image_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/pdf/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='pdf_image_3',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/pdf/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='pdf_image_4',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/pdf/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='pdf_image_5',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/pdf/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='pdf_image_6',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/pdf/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='pdf_image_7',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/pdf/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='pdf_image_8',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/quick_solutions/pdf/'),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='text_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='text_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='text_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='text_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='text_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicksolution',
            name='text_8',
            field=models.TextField(blank=True, null=True),
        ),
    ]
