# Generated by Django 5.1.1 on 2025-03-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0082_quicksolution_mobile_image_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickSolution',
        ),
    ]
