# Generated by Django 5.1.1 on 2025-03-01 11:31

import report_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0083_delete_quicksolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_mobile_icon',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_pdf_icon',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_correction_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_correction_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_correction_mobile_icon',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/emotional_correction_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_correction_pdf_icon',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/emotional_correction_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='lifestyle_correction_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='lifestyle_correction_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='lifestyle_correction_mobile_icon',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/lifestyle_correction_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='lifestyle_correction_pdf_icon',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/lifestyle_correction_icons/pdf/'),
        ),
    ]
