# Generated by Django 5.1.1 on 2025-03-01 11:58

import report_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0084_diagnosticresource_dietary_solution_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='dietary_solution_mobile_icon',
            new_name='dietary_solution_mobile_icon_1',
        ),
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='dietary_solution_pdf_icon',
            new_name='dietary_solution_pdf_icon_1',
        ),
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='emotional_correction_mobile_icon',
            new_name='emotional_correction_mobile_icon_1',
        ),
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='emotional_correction_pdf_icon',
            new_name='emotional_correction_pdf_icon_1',
        ),
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='lifestyle_correction_mobile_icon',
            new_name='lifestyle_correction_mobile_icon_1',
        ),
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='lifestyle_correction_pdf_icon',
            new_name='lifestyle_correction_pdf_icon_1',
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_mobile_icon_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_mobile_icon_3',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_mobile_icon_4',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_mobile_icon_5',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_mobile_icon_6',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_pdf_icon_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_pdf_icon_3',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_pdf_icon_4',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_pdf_icon_5',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='dietary_solution_pdf_icon_6',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/dietary_solution_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_correction_mobile_icon_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/emotional_correction_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_correction_pdf_icon_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/emotional_correction_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='lifestyle_correction_mobile_icon_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/lifestyle_correction_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='lifestyle_correction_pdf_icon_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/lifestyle_correction_icons/pdf/'),
        ),
    ]
