# Generated by Django 5.1.1 on 2025-03-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0085_rename_dietary_solution_mobile_icon_diagnosticresource_dietary_solution_mobile_icon_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlink',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionlink',
            name='questions_set',
        ),
        migrations.DeleteModel(
            name='QuestionModel',
        ),
        migrations.DeleteModel(
            name='QuestionLink',
        ),
        migrations.DeleteModel(
            name='QuestionsSet',
        ),
    ]
