# Generated by Django 5.1.1 on 2025-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0086_remove_questionlink_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name, e.g., 'wind yin', 'cold yin', etc.", max_length=100)),
                ('yin_yang', models.CharField(help_text="Either 'yin' or 'yang'", max_length=10)),
                ('question', models.TextField(help_text='The text of the question')),
                ('options', models.JSONField(default=list, help_text="List of options, e.g., ['Yes', 'No']")),
                ('picture_url', models.URLField(blank=True, help_text='Optional URL of a related picture', null=True)),
                ('created_by', models.CharField(help_text="Creator's name", max_length=100)),
                ('updated_by', models.CharField(help_text="Last updater's name", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'symptomsquestions',
            },
        ),
    ]
