# Generated by Django 5.1.1 on 2025-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0087_symptomsquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsquestions',
            name='created_by',
            field=models.CharField(blank=True, help_text="Creator's name (optional)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsquestions',
            name='updated_by',
            field=models.CharField(blank=True, help_text="Last updater's name (optional)", max_length=100, null=True),
        ),
    ]
