# Generated by Django 5.1.1 on 2025-03-05 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0088_alter_symptomsquestions_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patterns',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patterns',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patterns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patterns',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patterns',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patterns_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patterns',
            name='yin_yang',
            field=models.CharField(blank=True, choices=[('yin', 'Yin'), ('yang', 'Yang')], max_length=10, null=True),
        ),
    ]
