# Generated by Django 5.1.1 on 2025-03-05 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0090_alter_patterns_pattern_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisreporthistory',
            name='report_pattern_type',
            field=models.ForeignKey(blank=True, db_column='report_pattern_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_reports', to='report_service.patterns', to_field='pattern_number'),
        ),
    ]
