# Generated by Django 5.1.1 on 2025-03-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0091_alter_diagnosisreporthistory_report_pattern_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomsquestions',
            name='question_number',
            field=models.IntegerField(default=1, help_text='The sequential number for the question'),
        ),
    ]
