# Generated by Django 5.1.1 on 2025-03-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0092_symptomsquestions_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsquestions',
            name='question_number',
            field=models.IntegerField(help_text='The sequential number for the question', unique=True),
        ),
    ]
