# Generated by Django 5.1.1 on 2025-03-06 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0093_alter_symptomsquestions_question_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_report_history', models.ForeignKey(db_column='report_history_id', on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_answers', to='report_service.diagnosisreporthistory')),
                ('symptom_question', models.ForeignKey(db_column='question_number', on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_answers', to='report_service.symptomsquestions', to_field='question_number')),
            ],
        ),
    ]
