# Generated by Django 5.1.1 on 2025-03-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0094_diagnosisanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomsquestions',
            name='disable',
            field=models.BooleanField(default=False, help_text='Disable this question. Check to disable.'),
        ),
        migrations.AlterField(
            model_name='symptomsquestions',
            name='yin_yang',
            field=models.CharField(choices=[('yin', 'Yin'), ('yang', 'Yang')], help_text="Either 'yin' or 'yang'", max_length=10),
        ),
    ]
