# Generated by Django 5.1.1 on 2025-03-06 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0095_symptomsquestions_disable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsquestions',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who created the question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_symptomsquestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='symptomsquestions',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who last updated the question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_symptomsquestions', to=settings.AUTH_USER_MODEL),
        ),
    ]
