# Generated by Django 5.1.1 on 2025-03-08 07:42

import report_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0096_alter_symptomsquestions_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='emotional_correction_1',
            new_name='emotional_lifestyle_correction_1',
        ),
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='emotional_correction_2',
            new_name='emotional_lifestyle_correction_2',
        ),
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='lifestyle_correction_1',
            new_name='emotional_lifestyle_correction_3',
        ),
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='lifestyle_correction_2',
            new_name='emotional_lifestyle_correction_4',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='emotional_correction_mobile_icon_1',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='emotional_correction_mobile_icon_2',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='emotional_correction_pdf_icon_1',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='emotional_correction_pdf_icon_2',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='lifestyle_correction_mobile_icon_1',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='lifestyle_correction_mobile_icon_2',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='lifestyle_correction_pdf_icon_1',
        ),
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='lifestyle_correction_pdf_icon_2',
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_lifestyle_correction_pdf_icon_1',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/emotional_lifestyle_correction_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_lifestyle_correction_pdf_icon_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/emotional_lifestyle_correction_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_lifestyle_correction_pdf_icon_3',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/emotional_lifestyle_correction_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='emotional_lifestyle_correction_pdf_icon_4',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/emotional_lifestyle_correction_icons/pdf/'),
        ),
    ]
