# Generated by Django 5.1.1 on 2025-03-09 08:05

import report_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0097_rename_emotional_correction_1_diagnosticresource_emotional_lifestyle_correction_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='tridosha_mobile_icon',
            new_name='tridosha_mobile_icon_1',
        ),
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='tridosha_pdf_icon',
            new_name='tridosha_pdf_icon_1',
        ),
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='tridosha_text',
            new_name='tridosha_text_1',
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='tridosha_mobile_icon_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/tridosha_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='tridosha_mobile_icon_3',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/tridosha_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='tridosha_pdf_icon_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/tridosha_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='tridosha_pdf_icon_3',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/tridosha_icons/pdf/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='tridosha_text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticresource',
            name='tridosha_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
