# Generated by Django 5.1.1 on 2025-03-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0098_rename_tridosha_mobile_icon_diagnosticresource_tridosha_mobile_icon_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticresource',
            name='body_anotations',
            field=models.CharField(blank=True, help_text='Enter comma-separated annotations.', max_length=255),
        ),
    ]
