# Generated by Django 5.1.1 on 2025-03-10 09:33

import report_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0099_diagnosticresource_body_anotations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='pulse_mobile_icon',
            new_name='pulse_mobile_icon_1',
        ),
        migrations.RenameField(
            model_name='diagnosticresource',
            old_name='pulse_pdf_icon',
            new_name='pulse_pdf_icon_1',
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='pulse_mobile_icon_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/pulse_icons/mobile/'),
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='pulse_pdf_icon_2',
            field=models.ImageField(blank=True, null=True, storage=report_service.utils.DiagnosticResourceStorage(), upload_to='diagnostic/pulse_icons/pdf/'),
        ),
    ]
