# Generated by Django 5.1.1 on 2025-03-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0101_diagnosticresource_ai_prediction_text5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='acupressure_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='heart_yin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
