# Generated by Django 5.1.1 on 2025-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0102_diagnosisreporthistory_acupressure_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomsquestions',
            name='organ',
            field=models.CharField(blank=True, choices=[('Lv', 'Lv'), ('GB', 'GB'), ('Heart', 'Heart'), ('SI', 'SI'), ('Sp', 'Sp'), ('St', 'St'), ('Lun', 'Lun'), ('LI', 'LI'), ('Kidney', 'Kidney'), ('UB', 'UB')], help_text='Select an organ: Lv, GB, Heart, SI, Sp, St, Lun, LI, v', max_length=10, null=True),
        ),
    ]
