# Generated by Django 5.1.1 on 2025-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0103_symptomsquestions_organ'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='processed',
            field=models.IntegerField(default=0),
        ),
    ]
