# Generated by Django 5.1.1 on 2025-03-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0104_diagnosisreporthistory_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='seed_organ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='seed_yin_yang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
