# Generated by Django 5.1.1 on 2025-03-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0105_diagnosisreporthistory_seed_organ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
