# Generated by Django 5.1.1 on 2025-03-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0106_diagnosisreporthistory_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='download_pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
