# Generated by Django 5.1.1 on 2025-03-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0107_diagnosisreporthistory_download_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticresource',
            name='yin_yang',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
