# Generated by Django 5.1.1 on 2025-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0108_alter_diagnosticresource_yin_yang'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='single_seed_page_number',
            field=models.IntegerField(blank=True, help_text='Stores the page number for the single seed page', null=True),
        ),
    ]
