# Generated by Django 5.1.1 on 2025-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0109_diagnosisreporthistory_single_seed_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreporthistory',
            name='flag',
            field=models.BooleanField(default=False, help_text='Set to True for Yes (1) and False for No (0).'),
        ),
    ]
