# Generated by Django 5.1.1 on 2025-04-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0110_diagnosisreporthistory_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticresource',
            name='pulse_mobile_image',
        ),
        migrations.AddField(
            model_name='diagnosticresource',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Kannada', 'Kannada'), ('Telugu', 'Telugu'), ('Hindi', 'Hindi')], default='English', max_length=50),
        ),
    ]
