# Generated by Django 5.1.1 on 2025-04-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0111_remove_diagnosticresource_pulse_mobile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticresource',
            name='pattern_number',
            field=models.CharField(max_length=50),
        ),
    ]
