# Generated by Django 5.1.1 on 2025-04-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0112_alter_diagnosticresource_pattern_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomsquestions',
            name='question_kannada',
            field=models.TextField(blank=True, help_text='The text of the Kannada question', null=True),
        ),
    ]
