# Generated by Django 5.1.1 on 2025-04-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0113_symptomsquestions_question_kannada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticresource',
            name='language',
            field=models.CharField(blank=True, choices=[('eng', 'English'), ('kan', 'Kannada'), ('tel', 'Telugu'), ('hin', 'Hindi')], default='eng', max_length=3, null=True),
        ),
    ]
