# Generated by Django 5.1.1 on 2025-04-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_service', '0114_alter_diagnosticresource_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticresource',
            name='language',
            field=models.CharField(blank=True, choices=[('eng', 'eng'), ('kan', 'kan'), ('tel', 'tel'), ('hin', 'hin')], default='eng', max_length=3, null=True),
        ),
    ]
