# Generated by Django 5.1.1 on 2024-11-18 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 58, 1, 888234, tzinfo=datetime.timezone.utc)),
        ),
    ]
