# Generated by Django 5.1.1 on 2024-11-18 14:03

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_forgotpasswordotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordotp',
            name='expires_at',
            field=models.DateTimeField(default=authentication.models.default_expiration),
        ),
    ]
