# Generated by Django 5.1.1 on 2024-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpayment',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
