# Generated by Django 5.1.1 on 2024-11-19 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_payments', '0003_reporttransactionhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletPayment',
            new_name='WalletPaymentsDetails',
        ),
        migrations.RenameModel(
            old_name='TransactionDetails',
            new_name='WalletTransactionDetails',
        ),
        migrations.AlterModelTable(
            name='walletpaymentsdetails',
            table='wallet_payment_details',
        ),
        migrations.AlterModelTable(
            name='wallettransactiondetails',
            table='wallet_transaction_details',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nadiswara_services',
            },
        ),
        migrations.CreateModel(
            name='ServiceTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_payments.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_transaction_details',
            },
        ),
        migrations.DeleteModel(
            name='ReportTransactionHistory',
        ),
    ]
