# Generated by Django 5.1.1 on 2024-11-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_payments', '0005_servicetransactiondetails_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactiondetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
