# Generated by Django 5.1.1 on 2024-11-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_payments', '0006_wallettransactiondetails_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetransactiondetails',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulse_payments.service'),
        ),
    ]
