# Generated by Django 5.1.1 on 2025-01-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_payments', '0007_alter_servicetransactiondetails_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='number_of_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
