# Generated by Django 5.1.1 on 2025-01-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_payments', '0008_service_image_url_service_number_of_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
