# Generated by Django 5.1.1 on 2025-01-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_payments', '0009_service_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
