# Generated by Django 5.1.1 on 2025-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_payments', '0010_alter_service_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimumBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'minimum_balance',
            },
        ),
    ]
