# Generated by Django 5.1.1 on 2025-03-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_payments', '0011_minimumbalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minimumbalance',
            options={'verbose_name': 'Minimum Balance', 'verbose_name_plural': 'Minimum Balance'},
        ),
    ]
