# Generated by Django 5.1.1 on 2025-04-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_payments', '0013_minimumbalance_created_at_minimumbalance_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetransactiondetails',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicetransactiondetails',
            name='report_history_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicetransactiondetails',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulse_payments.service', to_field='service_id'),
        ),
    ]
