# Generated by Django 5.1.1 on 2025-01-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
