# Generated by Django 5.1.1 on 2025-02-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
