# Generated by Django 5.1.1 on 2025-02-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userprofile_age_userprofile_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dob',
            new_name='age',
        ),
    ]
