# Generated by Django 5.1.1 on 2025-02-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_rename_dob_userprofile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='age',
            new_name='dob',
        ),
    ]
