# Generated by Django 5.1.1 on 2024-12-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registersensor',
            name='is_prime_member',
            field=models.BooleanField(default=False, help_text='Indicates if the sensor user is a prime member'),
        ),
    ]
