# Generated by Django 5.1.1 on 2024-12-14 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0002_registersensor_is_prime_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factorysenorlist',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this sensor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sensors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registersensor',
            name='unique_id',
            field=models.ForeignKey(help_text='Unique identifier for the sensor', on_delete=django.db.models.deletion.CASCADE, to='device_management.factorysenorlist', to_field='unique_id'),
        ),
    ]
