# Generated by Django 5.1.1 on 2024-12-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0003_factorysenorlist_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registersensor',
            name='unique_id',
            field=models.ForeignKey(db_column='unique_id', help_text='Unique identifier for the sensor', on_delete=django.db.models.deletion.CASCADE, to='device_management.factorysenorlist', to_field='unique_id'),
        ),
    ]
