# Generated by Django 5.1.1 on 2025-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0004_alter_registersensor_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registersensor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registersensor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
