# Generated by Django 5.1.1 on 2024-12-30 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_service', '0042_remove_auricularreportsystem_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuricularProtocolBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.TextField(blank=True, help_text='Select multiple protocols for Protocol 1 (comma-separated values).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auricular_protocols_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auricular_protocols_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auricular_protocol_bank',
            },
        ),
        migrations.CreateModel(
            name='AuricularReportSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocols', models.TextField(blank=True, help_text='Select multiple protocols as comma-separated values (stored as IDs).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auricular_reports_created_by', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='auricular_report_systems', to='report_service.diagnosticresource')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auricular_reports_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auricular_report_system',
            },
        ),
        migrations.CreateModel(
            name='MudraProtocolBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, choices=[('Vayu Mudra', 'Vayu Mudra'), ('Jala Mudra', 'Jala Mudra'), ('Prana Mudra', 'Prana Mudra')], help_text='Select a Mudra Protocol', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mudra_protocols_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mudra_protocols_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mudra_protocol_bank',
            },
        ),
        migrations.CreateModel(
            name='MudraReportSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocols', models.TextField(blank=True, help_text='Select multiple protocols as comma-separated values (stored as IDs).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mudra_reports_created_by', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='mudra_report_systems', to='report_service.diagnosticresource')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mudra_reports_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mudra_report_system',
            },
        ),
        migrations.CreateModel(
            name='ReportSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auricular_protocol', models.CharField(blank=True, help_text='Select protocols for auricular reports (multiple selections allowed).', max_length=255)),
                ('color_therapy_protocol', models.CharField(blank=True, help_text='Select protocols for color therapy (multiple selections allowed).', max_length=255)),
                ('seed_therapy_protocol', models.CharField(blank=True, help_text='Select protocols for seed therapy (multiple selections allowed).', max_length=255)),
                ('single_point_protocol', models.CharField(blank=True, help_text='Select protocols for single point reports (multiple selections allowed).', max_length=255)),
                ('acupressure_protocol', models.CharField(blank=True, help_text='Select protocols for acupressure (multiple selections allowed).', max_length=255)),
                ('mudra_protocol', models.CharField(blank=True, help_text='Select protocols for mudra (multiple selections allowed).', max_length=255)),
                ('yoga_protocol', models.CharField(blank=True, help_text='Select protocols for yoga (multiple selections allowed).', max_length=255)),
                ('pranayama_protocol', models.CharField(blank=True, help_text='Select protocols for pranayama (multiple selections allowed).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_selectors_created_by', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='report_selectors', to='report_service.diagnosticresource')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_selectors_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_selector',
            },
        ),
    ]
