# Generated by Django 5.1.1 on 2025-01-01 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0001_initial'),
        ('report_service', '0046_alter_patterns_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricularreportsystem',
            name='report',
            field=models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='auricular_report_systems', to='report_service.patterns'),
        ),
    ]
