# Generated by Django 5.1.1 on 2025-01-01 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0002_alter_auricularreportsystem_report'),
        ('report_service', '0047_alter_diagnosisreporthistory_report_pattern_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mudrareportsystem',
            name='report',
            field=models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='mudra_report_systems', to='report_service.patterns'),
        ),
    ]
