# Generated by Django 5.1.1 on 2025-01-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0003_alter_mudrareportsystem_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_note', models.TextField(help_text='Details of the treatment note')),
                ('base_image', models.ImageField(blank=True, help_text='Upload the base image', null=True, upload_to='base_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='mudraprotocolbank',
            name='protocol',
            field=models.CharField(blank=True, choices=[('Aakash Mudra', 'Aakash Mudra'), ('Adi Mudra', 'Adi Mudra'), ('Apaan Mudra', 'Apaan Mudra')], help_text='Select a Mudra Protocol', max_length=255),
        ),
    ]
