# Generated by Django 5.1.1 on 2025-01-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0004_auricular_alter_mudraprotocolbank_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricular',
            name='base_image',
            field=models.URLField(blank=True, help_text='URL of the base image', null=True),
        ),
    ]
