# Generated by Django 5.1.1 on 2025-01-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0005_alter_auricular_base_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='disable_treatment_notes',
            field=models.BooleanField(default=False, help_text='Check this box to disable base notes.'),
        ),
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='protocol_notes',
            field=models.TextField(blank=True, help_text='Additional notes for the protocol.', null=True),
        ),
    ]
