# Generated by Django 5.1.1 on 2025-01-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0006_auricularprotocolbank_disable_treatment_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auricular',
            table='auricular',
        ),
    ]
