# Generated by Django 5.1.1 on 2025-01-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0007_alter_auricular_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportSelector',
        ),
    ]
