# Generated by Django 5.1.1 on 2025-01-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0008_delete_reportselector'),
    ]

    operations = [
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='base_image',
            field=models.URLField(blank=True, help_text='URL of the base image for the protocol.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='related_image_1',
            field=models.URLField(blank=True, help_text='URL of the first related image.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='related_image_2',
            field=models.URLField(blank=True, help_text='URL of the second related image.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='related_image_3',
            field=models.URLField(blank=True, help_text='URL of the third related image.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mudraprotocolbank',
            name='base_image',
            field=models.URLField(blank=True, help_text='URL of the base image for the protocol.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mudraprotocolbank',
            name='related_image_1',
            field=models.URLField(blank=True, help_text='URL of the first related image.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mudraprotocolbank',
            name='related_image_2',
            field=models.URLField(blank=True, help_text='URL of the second related image.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mudraprotocolbank',
            name='related_image_3',
            field=models.URLField(blank=True, help_text='URL of the third related image.', max_length=500, null=True),
        ),
    ]
