# Generated by Django 5.1.1 on 2025-01-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0009_auricularprotocolbank_base_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mudra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_note', models.TextField(help_text='Details of the treatment note')),
                ('base_image', models.URLField(blank=True, help_text='URL of the base image', null=True)),
            ],
            options={
                'db_table': 'mudra',
            },
        ),
        migrations.AddField(
            model_name='mudraprotocolbank',
            name='protocol_notes',
            field=models.TextField(blank=True, help_text='Additional notes for the protocol.', null=True),
        ),
    ]
