# Generated by Django 5.1.1 on 2025-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0010_mudra_mudraprotocolbank_protocol_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mudraprotocolbank',
            name='disable_treatment_notes',
            field=models.BooleanField(default=False, help_text='Check this box to disable base notes.'),
        ),
    ]
