# Generated by Django 5.1.1 on 2025-01-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0011_mudraprotocolbank_disable_treatment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='disable_root_base_image',
            field=models.BooleanField(default=False, help_text='Check this box to disable root base image.'),
        ),
    ]
