# Generated by Django 5.1.1 on 2025-01-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0013_auricularprotocolbank_protocol_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auricular',
            old_name='base_image',
            new_name='base_image_1',
        ),
        migrations.RenameField(
            model_name='mudra',
            old_name='base_image',
            new_name='base_image_1',
        ),
        migrations.AddField(
            model_name='auricular',
            name='base_image_2',
            field=models.URLField(blank=True, help_text='URL of the base image', null=True),
        ),
        migrations.AddField(
            model_name='mudra',
            name='base_image_2',
            field=models.URLField(blank=True, help_text='URL of the base image', null=True),
        ),
    ]
