# Generated by Django 5.1.1 on 2025-01-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0014_rename_base_image_auricular_base_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricular',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AlterField(
            model_name='auricular',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AlterField(
            model_name='mudra',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AlterField(
            model_name='mudra',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
    ]
