# Generated by Django 5.1.1 on 2025-01-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0016_mudraprotocolbank_disable_root_base_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auricularprotocolbank',
            old_name='base_image',
            new_name='base_image_1',
        ),
        migrations.RenameField(
            model_name='mudraprotocolbank',
            old_name='base_image',
            new_name='base_image_1',
        ),
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='base_image_2',
            field=models.URLField(blank=True, help_text='URL of the base image for the protocol.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mudraprotocolbank',
            name='base_image_2',
            field=models.URLField(blank=True, help_text='URL of the base image for the protocol.', max_length=500, null=True),
        ),
    ]
