# Generated by Django 5.1.1 on 2025-01-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0018_alter_auricularprotocolbank_base_image_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auricularprotocolbank',
            old_name='related_image_1',
            new_name='reference_image_1',
        ),
        migrations.RenameField(
            model_name='auricularprotocolbank',
            old_name='related_image_2',
            new_name='reference_image_2',
        ),
        migrations.RenameField(
            model_name='auricularprotocolbank',
            old_name='related_image_3',
            new_name='reference_image_3',
        ),
        migrations.RenameField(
            model_name='mudraprotocolbank',
            old_name='related_image_1',
            new_name='reference_image_1',
        ),
        migrations.RenameField(
            model_name='mudraprotocolbank',
            old_name='related_image_2',
            new_name='reference_image_2',
        ),
        migrations.RenameField(
            model_name='mudraprotocolbank',
            old_name='related_image_3',
            new_name='reference_image_3',
        ),
    ]
