# Generated by Django 5.1.1 on 2025-01-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0019_rename_related_image_1_auricularprotocolbank_reference_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='reference_image_4',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AddField(
            model_name='auricularprotocolbank',
            name='reference_image_5',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AddField(
            model_name='mudraprotocolbank',
            name='reference_image_4',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AddField(
            model_name='mudraprotocolbank',
            name='reference_image_5',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='reference_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='reference_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='reference_image_3',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AlterField(
            model_name='mudraprotocolbank',
            name='reference_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AlterField(
            model_name='mudraprotocolbank',
            name='reference_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
        migrations.AlterField(
            model_name='mudraprotocolbank',
            name='reference_image_3',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, upload_to='treatment_images/'),
        ),
    ]
