# Generated by Django 5.1.1 on 2025-03-09 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0022_colour_alter_auricular_options_and_more'),
        ('report_service', '0097_rename_emotional_correction_1_diagnosticresource_emotional_lifestyle_correction_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricularreportsystem',
            name='report',
            field=models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related_reports', to='report_service.patterns', to_field='pattern_number'),
        ),
        migrations.AlterField(
            model_name='colourreportsystem',
            name='report',
            field=models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related_reports', to='report_service.patterns', to_field='pattern_number'),
        ),
        migrations.AlterField(
            model_name='mudrareportsystem',
            name='report',
            field=models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related_reports', to='report_service.patterns', to_field='pattern_number'),
        ),
        migrations.AlterField(
            model_name='yogareportsystem',
            name='report',
            field=models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related_reports', to='report_service.patterns', to_field='pattern_number'),
        ),
    ]
