# Generated by Django 5.1.1 on 2025-03-10 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0024_singleseed_singleseedprotocolbank_and_more'),
        ('report_service', '0100_rename_pulse_mobile_icon_diagnosticresource_pulse_mobile_icon_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auricular_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('seed_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('single_point_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('colour_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('yoga_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('mudra_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('pranayama_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('report_history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_histories', to='report_service.diagnosisreporthistory')),
            ],
            options={
                'db_table': 'treatment_history',
            },
        ),
    ]
