# Generated by Django 5.1.1 on 2025-03-10 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0025_treatmenthistory'),
        ('patients', '0006_remove_patientsmodel_age_patientsmodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmenthistory',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_histories', to='patients.patientsmodel'),
        ),
    ]
