# Generated by Django 5.1.1 on 2025-03-11 08:03

import dynamic_report_service.models
import dynamic_report_service.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0026_treatmenthistory_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricular',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image),
        ),
        migrations.AlterField(
            model_name='auricular',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Another image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (base_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_1'})),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (base_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_2'})),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='reference_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_1'})),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='reference_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_2'})),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='reference_image_3',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_3)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_3'})),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='reference_image_4',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_4)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_4'})),
        ),
        migrations.AlterField(
            model_name='auricularprotocolbank',
            name='reference_image_5',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_5)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_5'})),
        ),
        migrations.AlterField(
            model_name='colour',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image),
        ),
        migrations.AlterField(
            model_name='colour',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Another image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image),
        ),
        migrations.AlterField(
            model_name='colourprotocolbank',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (base_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_1'})),
        ),
        migrations.AlterField(
            model_name='colourprotocolbank',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (base_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_2'})),
        ),
        migrations.AlterField(
            model_name='colourprotocolbank',
            name='reference_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_1'})),
        ),
        migrations.AlterField(
            model_name='colourprotocolbank',
            name='reference_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_2'})),
        ),
        migrations.AlterField(
            model_name='colourprotocolbank',
            name='reference_image_3',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_3)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_3'})),
        ),
        migrations.AlterField(
            model_name='colourprotocolbank',
            name='reference_image_4',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_4)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_4'})),
        ),
        migrations.AlterField(
            model_name='colourprotocolbank',
            name='reference_image_5',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_5)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_5'})),
        ),
        migrations.AlterField(
            model_name='mudra',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image),
        ),
        migrations.AlterField(
            model_name='mudra',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Another image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image),
        ),
        migrations.AlterField(
            model_name='mudraprotocolbank',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (base_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_1'})),
        ),
        migrations.AlterField(
            model_name='mudraprotocolbank',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (base_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_2'})),
        ),
        migrations.AlterField(
            model_name='mudraprotocolbank',
            name='reference_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_1'})),
        ),
        migrations.AlterField(
            model_name='mudraprotocolbank',
            name='reference_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_2'})),
        ),
        migrations.AlterField(
            model_name='mudraprotocolbank',
            name='reference_image_3',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_3)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_3'})),
        ),
        migrations.AlterField(
            model_name='mudraprotocolbank',
            name='reference_image_4',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_4)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_4'})),
        ),
        migrations.AlterField(
            model_name='mudraprotocolbank',
            name='reference_image_5',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_5)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_5'})),
        ),
        migrations.AlterField(
            model_name='singleseed',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image),
        ),
        migrations.AlterField(
            model_name='singleseed',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Another image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image),
        ),
        migrations.AlterField(
            model_name='singleseedprotocolbank',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (base_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_1'})),
        ),
        migrations.AlterField(
            model_name='singleseedprotocolbank',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (base_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_2'})),
        ),
        migrations.AlterField(
            model_name='singleseedprotocolbank',
            name='reference_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_1'})),
        ),
        migrations.AlterField(
            model_name='singleseedprotocolbank',
            name='reference_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_2'})),
        ),
        migrations.AlterField(
            model_name='singleseedprotocolbank',
            name='reference_image_3',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_3)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_3'})),
        ),
        migrations.AlterField(
            model_name='singleseedprotocolbank',
            name='reference_image_4',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_4)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_4'})),
        ),
        migrations.AlterField(
            model_name='singleseedprotocolbank',
            name='reference_image_5',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_5)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_5'})),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Another image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image),
        ),
        migrations.AlterField(
            model_name='yogaprotocolbank',
            name='base_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (base_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_1'})),
        ),
        migrations.AlterField(
            model_name='yogaprotocolbank',
            name='base_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (base_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_2'})),
        ),
        migrations.AlterField(
            model_name='yogaprotocolbank',
            name='reference_image_1',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_1'})),
        ),
        migrations.AlterField(
            model_name='yogaprotocolbank',
            name='reference_image_2',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_2'})),
        ),
        migrations.AlterField(
            model_name='yogaprotocolbank',
            name='reference_image_3',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_3)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_3'})),
        ),
        migrations.AlterField(
            model_name='yogaprotocolbank',
            name='reference_image_4',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_4)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_4'})),
        ),
        migrations.AlterField(
            model_name='yogaprotocolbank',
            name='reference_image_5',
            field=models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_5)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_5'})),
        ),
    ]
