# Generated by Django 5.1.1 on 2025-03-12 05:41

import django.db.models.deletion
import dynamic_report_service.models
import dynamic_report_service.utils
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0027_alter_auricular_base_image_1_and_more'),
        ('report_service', '0100_rename_pulse_mobile_icon_diagnosticresource_pulse_mobile_icon_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seedtherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_note', models.TextField(help_text='Details of the treatment note')),
                ('base_image_1', models.ImageField(blank=True, help_text='Image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image)),
                ('base_image_2', models.ImageField(blank=True, help_text='Another image of the treatment base', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=dynamic_report_service.models.TreatmentBase.upload_to_base_image)),
            ],
            options={
                'verbose_name': 'Seed therapy',
                'verbose_name_plural': 'Seed therapy',
                'db_table': 'seed_therapy',
            },
        ),
        migrations.CreateModel(
            name='SeedtherapyProtocolBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (56, '56'), (57, '57'), (58, '58'), (59, '59'), (60, '60')], help_text='Select a unique protocol number (1 to 60).', null=True, unique=True)),
                ('protocol', models.TextField(blank=True, help_text='Select multiple protocols for Protocol 1 (comma-separated values).')),
                ('disable_root_base_image', models.BooleanField(default=False, help_text='Check this box to disable root base image.')),
                ('disable_treatment_notes', models.BooleanField(default=False, help_text='Check this box to disable base notes.')),
                ('protocol_notes', models.TextField(blank=True, help_text='Additional notes for the protocol.', null=True)),
                ('base_image_1', models.ImageField(blank=True, help_text='Image of the treatment base (base_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_1'}))),
                ('base_image_2', models.ImageField(blank=True, help_text='Image of the treatment base (base_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'base_image_2'}))),
                ('reference_image_1', models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_1)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_1'}))),
                ('reference_image_2', models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_2)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_2'}))),
                ('reference_image_3', models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_3)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_3'}))),
                ('reference_image_4', models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_4)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_4'}))),
                ('reference_image_5', models.ImageField(blank=True, help_text='Image of the treatment base (reference_image_5)', null=True, storage=dynamic_report_service.utils.TreatmentResourceStorage(), upload_to=functools.partial(dynamic_report_service.models.upload_to_protocol_image, *(), **{'protocol_image_name': 'reference_image_5'}))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seed therapy Protocol Bank',
                'verbose_name_plural': 'Seed therapy Protocol Bank',
                'db_table': 'seed_therapy_protocol_bank',
            },
        ),
        migrations.CreateModel(
            name='SeedtherapyReportSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocols', models.TextField(blank=True, help_text='Select multiple protocols as comma-separated values (stored as IDs).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='Select the diagnostic report.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related_reports', to='report_service.patterns', to_field='pattern_number')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seed therapy Report System',
                'verbose_name_plural': 'Seed therapy Report System',
                'db_table': 'seed_therapy_report_system',
            },
        ),
    ]
