# Generated by Django 5.1.1 on 2025-03-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0029_acupressure_acupressureprotocolbank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleseedprotocolbank',
            name='protocol_number',
        ),
        migrations.AddField(
            model_name='singleseedprotocolbank',
            name='organ',
            field=models.CharField(blank=True, choices=[('Lv', 'Lv'), ('GB', 'GB'), ('Heart', 'Heart'), ('SI', 'SI'), ('Sp', 'Sp'), ('St', 'St'), ('Lun', 'Lun'), ('LI', 'LI'), ('Kidney', 'Kidney'), ('UB', 'UB')], help_text='Select an organ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='singleseedprotocolbank',
            name='yin_yang',
            field=models.CharField(blank=True, choices=[('yin', 'yin'), ('yang', 'yang')], help_text='Select either yin or yang', max_length=10, null=True),
        ),
    ]
