# Generated by Django 5.1.1 on 2025-03-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_report_service', '0032_singleseedprotocolbank_protocol_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acupressure',
            name='treatment_note',
            field=models.TextField(blank=True, help_text='Details of the treatment note', null=True),
        ),
        migrations.AlterField(
            model_name='auricular',
            name='treatment_note',
            field=models.TextField(blank=True, help_text='Details of the treatment note', null=True),
        ),
        migrations.AlterField(
            model_name='colour',
            name='treatment_note',
            field=models.TextField(blank=True, help_text='Details of the treatment note', null=True),
        ),
        migrations.AlterField(
            model_name='mudra',
            name='treatment_note',
            field=models.TextField(blank=True, help_text='Details of the treatment note', null=True),
        ),
        migrations.AlterField(
            model_name='pranayama',
            name='treatment_note',
            field=models.TextField(blank=True, help_text='Details of the treatment note', null=True),
        ),
        migrations.AlterField(
            model_name='seedtherapy',
            name='treatment_note',
            field=models.TextField(blank=True, help_text='Details of the treatment note', null=True),
        ),
        migrations.AlterField(
            model_name='singleseed',
            name='treatment_note',
            field=models.TextField(blank=True, help_text='Details of the treatment note', null=True),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='treatment_note',
            field=models.TextField(blank=True, help_text='Details of the treatment note', null=True),
        ),
    ]
