# Generated by Django 5.1.1 on 2024-11-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('dob', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo_uri', models.URLField(blank=True, null=True)),
                ('family_member', models.IntegerField(default=1)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
            options={
                'db_table': 'patients_model',
                'unique_together': {('user_profile', 'name', 'phone_number')},
            },
        ),
    ]
