# Generated by Django 5.1.1 on 2024-11-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientsmodel_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsmodel',
            name='family_member',
        ),
    ]
