# Generated by Django 5.1.1 on 2024-12-01 08:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patientsmodel_family_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsmodel',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AlterUniqueTogether(
            name='patientsmodel',
            unique_together={('user_profile', 'first_name', 'phone_number')},
        ),
    ]
