# Generated by Django 5.1.1 on 2024-12-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_name_patientsmodel_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsmodel',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
