# Generated by Django 5.1.1 on 2024-12-02 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientsmodel_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='patientsmodel',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientsmodel',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patientsmodel',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientsmodel',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientsmodel',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
