# Generated by Django 5.1.1 on 2025-03-26 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patientsmodel_age_patientsmodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
