# Generated by Django 5.1.1 on 2024-11-19 13:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0002_alter_patientsmodel_user_profile"),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("pulse_uri", models.URLField()),
                ("signal_data", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        default=999999,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patientsmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "pulse_data",
            },
        ),
        migrations.CreateModel(
            name="PulseDataObservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urine_color",
                    models.CharField(
                        choices=[
                            (
                                "white_transparent_occasional",
                                "White Transparent Occasionally",
                            ),
                            ("white_transparent_always", "White Transparent Always"),
                            ("pale_yellow", "Pale Yellow"),
                            ("yellow_occasional", "Yellow Occasionally"),
                            ("yellow_always", "Yellow Always"),
                        ],
                        max_length=50,
                    ),
                ),
                ("night_urination", models.PositiveSmallIntegerField()),
                (
                    "sleep",
                    models.CharField(
                        choices=[
                            ("disturbed_occasionally", "Disturbed Occasionally"),
                            ("late_sleep", "Late Sleep"),
                            ("normal_sleep", "Normal Sleep"),
                            ("hard_to_sleep", "Hard to Get Sleep"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "backpain",
                    models.CharField(
                        choices=[
                            ("sometimes", "Sometimes"),
                            ("always", "Always"),
                            ("no", "No"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "appetite",
                    models.CharField(
                        choices=[
                            ("no_hunger", "No Hunger"),
                            ("less_hunger", "Less Hunger"),
                            ("normal_hunger", "Normal Hunger"),
                            ("more_hunger", "More Hunger"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "bowel_movement",
                    models.CharField(
                        choices=[
                            ("constipated_sometimes", "Constipated Sometimes"),
                            ("constipated_always", "Constipated Always"),
                            ("normal_bowel", "Normal Bowel"),
                            ("sometimes_loose_stools", "Sometimes Loose Stools"),
                            ("always_loose_stools", "Always Loose Stools"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "numbness",
                    models.CharField(
                        choices=[
                            ("not_feeling_numbness", "Not Feeling Numbness"),
                            ("sometimes_numbness", "Sometimes Numbness"),
                            ("always_numbness", "Always Numbness"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "headache",
                    models.CharField(
                        choices=[
                            ("no_headache", "Not Feeling Headache"),
                            ("back_of_head", "Back of the Head"),
                            ("one_side_head", "One Side of the Head"),
                            ("top_of_head", "Top of the Head"),
                            ("forehead", "Forehead Headache"),
                            ("whole_head", "Whole Head"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "pulse",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="pulse_service.pulsedata",
                    ),
                ),
            ],
            options={
                "db_table": "pulse_data_observations",
            },
        ),
        migrations.CreateModel(
            name="PulseDataSymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organ", models.CharField(max_length=50)),
                ("symptoms", models.CharField(max_length=50)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "pulse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ob",
                        to="pulse_service.pulsedata",
                    ),
                ),
            ],
            options={
                "db_table": "pulse_data_symptoms",
            },
        ),
    ]
