# Generated by Django 5.1.1 on 2025-01-27 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_service', '0002_alter_pulsedata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.TextField()),
                ('question_2', models.TextField()),
                ('question_3', models.TextField()),
                ('question_4', models.TextField()),
                ('question_5', models.TextField()),
                ('question_6', models.TextField()),
                ('question_7', models.TextField()),
                ('question_8', models.TextField()),
                ('question_9', models.TextField()),
                ('question_10', models.TextField()),
                ('question_11', models.TextField()),
                ('question_12', models.TextField()),
                ('question_13', models.TextField()),
                ('question_14', models.TextField()),
                ('question_15', models.TextField()),
                ('question_16', models.TextField()),
                ('question_17', models.TextField()),
                ('question_18', models.TextField()),
                ('question_19', models.TextField()),
                ('question_20', models.TextField()),
                ('question_21', models.TextField()),
                ('question_22', models.TextField()),
                ('question_23', models.TextField()),
                ('question_24', models.TextField()),
                ('question_25', models.TextField()),
                ('question_26', models.TextField()),
                ('question_27', models.TextField()),
                ('question_28', models.TextField()),
                ('question_29', models.TextField()),
                ('question_30', models.TextField()),
                ('question_31', models.TextField()),
                ('question_32', models.TextField()),
                ('question_33', models.TextField()),
                ('question_34', models.TextField()),
                ('question_35', models.TextField()),
                ('question_36', models.TextField()),
                ('question_37', models.TextField()),
                ('question_38', models.TextField()),
                ('question_39', models.TextField()),
                ('question_40', models.TextField()),
                ('question_41', models.TextField()),
                ('question_42', models.TextField()),
                ('question_43', models.TextField()),
                ('question_44', models.TextField()),
                ('question_45', models.TextField()),
                ('question_46', models.TextField()),
                ('question_47', models.TextField()),
                ('question_48', models.TextField()),
                ('question_49', models.TextField()),
                ('question_50', models.TextField()),
                ('pulse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_service.pulsedata')),
            ],
            options={
                'db_table': 'questions_table',
            },
        ),
    ]
