# Generated by Django 5.1.1 on 2025-01-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_service', '0003_questionstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pulse_log',
            },
        ),
    ]
