# Generated by Django 5.1.1 on 2025-03-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_service', '0005_question_questionset_option_question_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='set',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionSet',
        ),
    ]
